# Generated by Django 4.2.7 on 2023-11-08 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=150, unique=True)),
                ('text', models.TextField(unique=True)),
                ('author', models.CharField(max_length=255)),
                ('pub_date', models.DateTimeField(verbose_name='date published: 0000-00-00 00:00:00')),
                ('type', models.CharField(choices=[('AR', 'статья'), ('NW', 'новость')], max_length=2)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news', to='NewsPaper.category')),
            ],
        ),
    ]
